name: GitHub Self-Updating Repository

on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          ref: ics
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Create UFC.ics
        run: |
          bun install --frozen-lockfile
          bun run start
      - name: Push to repository
        run: |
          git config --global user.name "Clarence Chan"
          git config --global user.email "clarencechaan@icloud.com"
          git rm --ignore-unmatch UFC-PPV.ics
          git add UFC.ics UFC-Numbered.ics
          git commit -m "Update UFC.ics and UFC-Numbered.ics"
          git push -u origin ics
